title:              Toe Stew Brr DataStory
email:              bordereaux.hugo@gmail.com
description:        EPFL - ADA class - Toe Stew Brr DataStory
author:             Marguerite Thery, Alexander Sternfeld, Antoine Bonnet and Hugo Bordereaux
baseurl:            "/"
url:                "https://BDX786.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
